# Generated by Django 3.1 on 2020-08-11 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(default=None, max_length=90, unique=True, verbose_name='小区名称'),
        ),
        migrations.AlterField(
            model_name='communityschool',
            name='community',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_Community', to='find_house.community', to_field='name', verbose_name='小区'),
        ),
        migrations.AlterField(
            model_name='communityschool',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_school', to='find_house.school', to_field='name', verbose_name='学校'),
        ),
    ]
