# Generated by Django 3.1 on 2020-08-11 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('find_house', '0002_auto_20200811_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='advantage',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='优点'),
        ),
        migrations.AddField(
            model_name='house',
            name='area',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='面积'),
        ),
        migrations.AddField(
            model_name='house',
            name='build',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='楼栋'),
        ),
        migrations.AddField(
            model_name='house',
            name='flor',
            field=models.CharField(blank=True, default=None, max_length=40, verbose_name='楼层房号'),
        ),
        migrations.AddField(
            model_name='house',
            name='is_lift',
            field=models.BooleanField(choices=[(True, '有'), (False, '无')], default=True, verbose_name='是否有电梯'),
        ),
        migrations.AddField(
            model_name='house',
            name='is_park',
            field=models.BooleanField(choices=[(True, '有'), (False, '无')], default=True, verbose_name='是否有地下停车场'),
        ),
        migrations.AddField(
            model_name='house',
            name='is_two_year',
            field=models.BooleanField(choices=[(True, '是'), (False, '否')], default=True, verbose_name='是否满两年'),
        ),
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='总价(万元)'),
        ),
        migrations.AddField(
            model_name='house',
            name='record',
            field=models.CharField(blank=True, default=None, max_length=600, null=True, verbose_name='看房记录'),
        ),
        migrations.AddField(
            model_name='house',
            name='remark',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='house',
            name='shortcoming',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='缺点'),
        ),
        migrations.AddField(
            model_name='house',
            name='unit_type',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='statics/media/', verbose_name='户型图'),
        ),
        migrations.AddField(
            model_name='house',
            name='year',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='建筑年代'),
        ),
        migrations.AlterField(
            model_name='community',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='均价(万元)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='community',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_to_Community', to='find_house.community', to_field='name', verbose_name='小区'),
        ),
    ]
