# Generated by Django 3.1 on 2020-08-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_house', '0003_auto_20200811_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': '房屋列表', 'verbose_name_plural': '房屋列表'},
        ),
        migrations.AlterField(
            model_name='community',
            name='price',
            field=models.FloatField(blank=True, default='', null=True, verbose_name='均价(万元)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.FloatField(blank=True, default='', null=True, verbose_name='面积'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.FloatField(blank=True, default='', null=True, verbose_name='总价(万元)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='year',
            field=models.IntegerField(blank=True, default='', null=True, verbose_name='建筑年代'),
        ),
    ]
