# Generated by Django 3.1 on 2020-08-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_house', '0004_auto_20200811_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='record',
            field=models.TextField(blank=True, default=None, max_length=600, null=True, verbose_name='看房记录'),
        ),
        migrations.AlterField(
            model_name='house',
            name='unit_type',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/media/', verbose_name='户型图'),
        ),
    ]
