# Generated by Django 3.1 on 2020-08-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_house', '0005_auto_20200811_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='area',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/media/', verbose_name='片区图片'),
        ),
        migrations.AlterField(
            model_name='community',
            name='remark',
            field=models.TextField(blank=True, default=None, max_length=600, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='house',
            name='remark',
            field=models.TextField(blank=True, default=None, max_length=600, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='school',
            name='remark',
            field=models.TextField(blank=True, default=None, max_length=600, null=True, verbose_name='备注'),
        ),
    ]
