# Generated by Django 3.1 on 2020-09-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_house', '0008_auto_20200912_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='intention',
            field=models.BooleanField(choices=[(True, '有'), (False, '无')], default=True, verbose_name='是否有意向'),
        ),
    ]
