# Generated by Django 3.1 on 2020-09-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_house', '0010_auto_20200912_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='intention',
            field=models.IntegerField(choices=[(1, '非常满意'), (2, '满意'), (3, '一般'), (4, '不满意'), (5, '备选')], default=5, verbose_name='是否有意向'),
        ),
    ]
